[package]
name = "rhythmdeckmusic/rhythmdeck"
version = "0.1.2"
description = "RhythmDeck artist platform"

[fs]
"/public" = "./public"

[[command]]
name = "start"
module = "./server.js"
runner = "nodejs"
